--
-- PostgreSQL database dump
--

-- Dumped from database version 15.3
-- Dumped by pg_dump version 15.3

-- Started on 2023-05-21 20:59:34

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;
SET default_tablespace = '';
SET default_table_access_method = heap;

--
-- TOC entry 215 (class 1259 OID 16399)
-- Name: events; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.events (
    title text,
    description text,
    start_date text,
    end_date text,
    id integer NOT NULL
);


ALTER TABLE public.events OWNER TO postgres;

--
-- TOC entry 3334 (class 0 OID 0)
-- Dependencies: 215
-- Name: COLUMN events.title; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.events.title IS 'Title of the event';


--
-- TOC entry 3335 (class 0 OID 0)
-- Dependencies: 215
-- Name: COLUMN events.description; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.events.description IS 'Description of the event';


--
-- TOC entry 3336 (class 0 OID 0)
-- Dependencies: 215
-- Name: COLUMN events.start_date; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.events.start_date IS 'Start date of the event';


--
-- TOC entry 3337 (class 0 OID 0)
-- Dependencies: 215
-- Name: COLUMN events.end_date; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.events.end_date IS 'End date of the event';


--
-- TOC entry 3338 (class 0 OID 0)
-- Dependencies: 215
-- Name: COLUMN events.id; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.events.id IS 'Identity';


--
-- TOC entry 216 (class 1259 OID 16420)
-- Name: events_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3326 (class 0 OID 16399)
-- Dependencies: 215
-- Data for Name: events; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3339 (class 0 OID 0)
-- Dependencies: 216
-- Name: events_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.events_id_seq', 52, true);


-- Completed on 2023-05-21 20:59:34

--
-- PostgreSQL database dump complete
--

